### ISSUE TITLE
listen fails when run non-interactively

### ISSUE THREAD

**Issue by madeleineth** [stripe/stripe-cli#51]
### Issue

I am trying to run `stripe listen` non-interactively in one docker container to proxy events to a different docker container, so that I can validate my webhooks in an automated test.

I run:
```
stripe listen --device-name my-test --api-key sk_test_XXXX
```
The output is:
```
your device name has not been configured. Use `stripe configure` to set your device name
```
but if I then run:
```
stripe configure
```
it outputs:
```
unknown command "configure" for "stripe"
```

So, the issue is:
1. I don't know what a device is, but according to `stripe listen --help` I should be able to set this with `--device-name`. The first command should succeed as is.
2. The error output should not refer to a nonexistent command.

If I populate `~/.config/stripe/config.toml` directly instead of using command-line flags, `stripe listen` works great. (While undocumented, this might be a better idea regardless, because then I don't need to worry about my API key being in an error message if the command fails.)

### Environment
Ubuntu 18.04 running under Docker, Stripe CLI 0.2.3 installed via https://github.com/stripe/stripe-cli/releases/download/v0.2.3/stripe_0.2.3_linux_amd64.deb.

### Postscript

`stripe listen` is great. I've been wanting something like this for a long time.

**Comment by ob-stripe** [comment]
@madeleineth Thanks for the report! This error message is indeed incorrect, the command to configure the CLI with your account's API key and device name is `stripe login` instead of `stripe configure`.

Note that running `stripe login` will open a web browser to automatically create and retrieve a new API key for your account. You can also run `stripe login --interactive` to manually provide your API key and device name.

(The device name is simply an identifier for your machine, it defaults to your local hostname but can be anything you want.)

We will fix the error message to clarify the above soon.

**Comment by madeleineth** [comment]
@ob-stripe Is there a recommended procedure for non-interactive use (i.e. on CI), where neither a web browser nor `--interactive` is appropriate?

**Comment by ob-stripe** [comment]
@madeleineth You could create the configuration file manually in your container (it's read from `${XDG_CONFIG_HOME}/stripe/config.toml, or `$HOME/.config/stripe/config.toml` if `XDG_CONFIG_HOME` is not set), or you can set the API key and device name via environment variables: `STRIPE_SECRET_KEY` and `STRIPE_DEVICE_NAME` respectively.

Out of curiosity, would you find it helpful if we provided Docker images for the CLI?

**Comment by madeleineth** [comment]
@ob-stripe okay, cool. Thanks.

A Docker image wouldn't help me personally. The application in question uses a KMS instead of environment variables for secret management, so I need code running inside the container to get the API key, and I'd rather not be tied to whatever base image you decided on. An APT repository would be useful, though. I don't like hard-coding package version numbers, and I'm doing that now with the .deb URL.

**Comment by ob-stripe** [comment]
Understood, thanks for the feedback!

> An APT repository would be useful, though.

No ETA yet, but that's definitely something we want to provide.

**Comment by ob-stripe** [comment]
@madeleineth We have an APT repository now! You can find installation instructions here: https://github.com/stripe/stripe-cli/blob/c6e8852610fac29349754477c41ff60a402017dc/README.md#linux

**Comment by madeleineth** [comment]
@ob-stripe excellent, works great.

**Comment by Freezystem** [comment]
> Out of curiosity, would you find it helpful if we provided Docker images for the CLI?

@ob-stripe I'd love to be able to run Stripe-CLI in a docker container in my CI. I was about to create one on my own but if I could get an official and better maintained one it would be really helpful :)

**Comment by ob-stripe** [comment]
@Freezystem Done! https://hub.docker.com/r/stripe/stripe-cli

**Comment by Freezystem** [comment]
@ob-stripe 
> or you can set the API key and device name via environment variables: STRIPE_SECRET_KEY and STRIPE_DEVICE_NAME respectively.
Don't seem to work with the docker container:

```yml
# stripe config from docker-compose.yml
stripe:
    image: stripe/stripe-cli:v0.5.1
    command: listen --forward-to host.docker.internal:8080/stripe/webhooks
    environment:
      - STRIPE_SECRET_KEY=rk_test_***
      - STRIPE_DEVICE_NAME=device-name
```

and I get this error: 
> stripe_1       | your API key has not been configured. Use `stripe login` to set your API key

I've then tried to force environment variable injection through parameters:

```yml
# stripe config from docker-compose.yml
stripe:
    image: stripe/stripe-cli:v0.5.1
    command: listen --device-name ${STRIPE_DEVICE_NAME} --api-key ${STRIPE_SECRET_KEY} --forward-to host.docker.internal:8080/stripe/webhooks
    environment:
      - STRIPE_SECRET_KEY=rk_test_***
      - STRIPE_DEVICE_NAME=device-name
```

But get this error:
> stripe_1       | listen does not take any arguments. See `stripe listen --help` for supported flags and usage

Did I miss something ?

**Comment by tomer-stripe** [comment]
For setting `--device-name`, there was a bug there that I fixed in version 0.5.4 if you want to give that a shot! Sorry for the delay there

**Comment by tomer-stripe** [comment]
Hey all, closing this issue since it looks like we resolved the underlying issues with the listen command. If you're still having issues please open a new issue!

**Comment by aminnaggar** [comment]
Hey great work on providing a docker image for this. I'm running into the same issue as @Freezystem before me. I'm tryin to run this non-interactively, and I'm getting

> stripe_1  | your API key has not been configured. Use `stripe login` to set your API key

this is my configuration

```yml
  # stripe config from docker-compose.yml
  stripe:
    image: stripe/stripe-cli:v0.8.0
    command: listen --forward-to http://localhost:3030/webhooks/stripe
    environment:
      - STRIPE_SECRET_KEY=sk_test_***
      - STRIPE_DEVICE_NAME=my-laptop
```

What am I missing? Cheers

**Comment by ob-stripe** [comment]
Hey @aminnaggar, thanks for the report. I think support for setting the API key via an environment variable is broken in the current version (0.8.0). We will investigate and report back here soon. Sorry for the inconvenience!

**Comment by smithb1994** [comment]
Any update on this? I'm using stripe-cli latest and I still can't seem to get it to work with docker-compose. Are environment variables still broken?

**Comment by Freezystem** [comment]
Hi @smithb1994, I'm using it with docker-compose and it works.

Stripe CLI is declared like this in my `docker-compose.yml`:
```yml
stripe:
    image: stripe/stripe-cli:v1.2.2
    command: listen --api-key rk_test_*** --device-name "local-$USER-data" --forward-to host.docker.internal/stripe-hooks
```
Maybe you can share your config in order to be helped.

**Comment by smithb1994** [comment]
I'm particularly interested in setting stripe name and key through environment variables in a docker-compose yml file:

```yml
  # stripe config from docker-compose.yml
  stripe:
    image: stripe/stripe-cli:v1.2.2
    command: listen --forward-to http://localhost:3030/webhooks/stripe
    environment:
      - STRIPE_SECRET_KEY=sk_test_***
      - STRIPE_DEVICE_NAME=my-laptop
```
Or in this way
```yml
  # stripe config from docker-compose.yml
  stripe:
    image: stripe/stripe-cli:v1.2.2
    command: listen --api-key ${STRIPE_SECRET_KEY} --device-name ${STRIPE_DEVICE_NAME} --forward-to http://localhost:3030/webhooks/stripe
    environment:
      - STRIPE_SECRET_KEY=sk_test_***
      - STRIPE_DEVICE_NAME=my-laptop
```
Neither seem to work.
It's important to do it through an environment variable so that keys can be changed depending on the environment, without hard coding.

**Comment by smithb1994** [comment]
For those who may stumble upon this in the future, the solution is to create a `.env` file with your `docker-compose.yml`.  
  
.env file
```yml
STRIPE_SECRET_KEY=sk_test_***
STRIPE_DEVICE_NAME=my-laptop
```

docker-compose.yml
```yml
version: '3'
services:
  stripe:
    image: stripe/stripe-cli
    command: listen --api-key ${STRIPE_SECRET_KEY} --device-name ${STRIPE_DEVICE_NAME}
```
Then run
`$ docker-compose up stripe`

If you have `${...}` anywhere in your docker-compose file, it looks in `.env` for the value.

Hope this helps.

**Comment by smithb1994** [comment]
**UPDATE 2021**

For those looking to setup stripe cli webhooks with their docker-compose test environment, here's my setup:
  
.env file
```yml
STRIPE_PRIVATE_KEY=sk_test_***
```

docker-compose.yml
```yml
version: '3'
services:
  stripe:
    image: stripe/stripe-cli
    command: listen --api-key ${STRIPE_PRIVATE_KEY} --forward-to server:3000 -a

  server:
    ...
```
Then run
`$ docker-compose up`

Take note that the server service is a node server, accessible at localhost:3000.
The stripe service accesses it in the docker-compose network through `server:3000`.

Lastly, the `-a` flag allows us to listen to events triggered from the stripe test environment.
You can remove the `-a` flag if you want to only listen to events triggered locally.

Hope this helps.

**Comment by Saran33** [comment]
It's not ideal that we can't pass environment variables to `/bin/stripe`. For example, I would like to set the host without needing to add it to a .env file, so that this can be overridden when extending this base service in other compose files:
```yaml
  stripe_cli:
    image: stripe/stripe-cli
    env_file:
      - .env
    environment:
      API_HOST: some_host
    command: listen --forward-to http://$${API_HOST}:8123/api/v1/webhooks/stripe
```
The above `$${API_HOST}` will not be expanded correctly, presumably due to the entrypoint of the Stripe image being `/bin/stripe` rather than a shell. The only thing I would like in my .env file are values that are common to all compose projects.
